### ISSUE TITLE
data.FRETNUMBER being a <choice> data type

### ISSUE THREAD

**Issue by lpugin** [TransformingMusicology/mei-tmus#1]
How standard is the 'x'? 
https://github.com/TransformingMusicology/mei-tmus/blob/56936b68e5c6b759e4f94b3e735f748d5dd3a82e/schemata/frettab.odd#L41
Having a <choice> makes the type not easy to process automatically.

**Comment by lpugin** [comment]
Would -1 instead of 'x' be acceptable?

**Comment by TimCrawford** [comment]
Laurent,

I agree that this is logical (it’s kind of a ‘missing’ pitch/string). And the choice of value here is arbitrary.

We will just need to *render* it as an ‘x’ in one specific context which is not part of our initial spec. That is, in grid-type chord-symbols like:
[cid:F9078549-5BA2-4E4F-99E8-F78D161A295B@univie.ac.at]
The ‘0’ indicates an open string and the ‘x’ a string that must not be played.

But NB, we are not attempting to handle this kind of tablature at this stage.

Tim

On 2 Jun 2019, at 11:46, Laurent Pugin <notifications@github.com<mailto:notifications@github.com>> wrote:


Would -1 instead of 'x' be acceptable?

**Comment by ryaanahmed** [comment]
I agree with Tim. The coding doesn't matter; we just need to render an 'x' glyph for these. And this is something we don't really need to handle for a minimal viable version of a renderer at all.

FWIW, I don't handle these in the music21 module yet...

**Comment by lpugin** [comment]
Great. We can - at least for now - go for an integer data type.
